version: '3'

volumes:
  pg_data:
  static:
  media:

services:
  db:
    image: postgres:13
    volumes:
      - pg_data:/var/lib/postgresql/data
    env_file: 
      - .env
    ports:
      - "5432:5432"
  
  backend:
    container_name: foodgram-backend
    build: ./backend
    env_file: 
      - .env
    volumes:
      - static:/app/static
      - media:/app/media
    depends_on:
      - db

  frontend:
    container_name: foodgram-front
    build: ./frontend
    volumes:
      - ./frontend/build:/app/result_build/
    depends_on:
      - backend
  
  nginx:
    container_name: foodgram-proxy
    image: nginx:1.25.4-alpine
    ports:
      - "9500:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./frontend/build:/usr/share/nginx/html/
      - static:/app/static
      - media:/app/media
    depends_on:
      - backend
      - frontend
