# Generated by Django 4.2.16 on 2024-11-04 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='profile_image',
        ),
        migrations.AddField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, help_text='Необязательное поле. Загрузите изображение профиля.', null=True, upload_to='avatar/', verbose_name='Аватар'),
        ),
    ]
